Display pokemon number
maurigzo/pokedex pull request #1
Opened 2022-05-14 02:51 UTC by maurigzo

Modified the pokemonExpanded structure to add the number (id in the api), and send it to the displayPokemon function in PokedexTableViewCell from PokedexViewController to change the text value of numberLabel

<img width="469" alt="Screen Shot 2022-05-13 at 23 26 18" src="https://user-images.githubusercontent.com/28616843/168408041-4c7506ac-b992-4a8a-a773-a9a44fe929f2.png">

2022-05-15 01:27 UTC, mdb1 reviewed
Looking really good! Left a couple of comments for you to check, let me know what you think

2022-05-15 01:27 UTC, mdb1 commented on Pokedex/Model/Pokemon/PokemonExpanded.swift
> +        case name
`nit`: You can use this convention:
```suggestion
        case sprites, name
```

2022-05-15 01:27 UTC, mdb1 commented on Pokedex/Presentation/Pokedex/PokedexTableViewCell.swift
> +    func displayPokemon(name: String, number: Int, image: UIImage?) {
This method is starting to take a lot of parameters, we could create a new struct to contain them.
Example:
```swift
struct PokedexCellViewModel {
    let name: String
    let number: Int
    let image: UIImage?
}
```

After that, we could use our new model as the parameter for this function:
`func displayPokemon(_ model: PokedexCellViewModel)`

Lastly, we could add one method to our new model to hold the display logic of the number:
```swift
extension PokedexCellViewModel {
    var numberText: String {
        "#\(number)"
    }
}
```

And then use it in the `displayPokemon` method.

One additional benefit of doing that is that we could add unit tests to this computed property:

```swift
func testPokedexCellNumberText() {
    // Given
    let pokedexCellModel = PokedexCellViewModel(name: "Bauri", number: 5, image: nil)
    let expectedResult = "#5"
     
    // When
    let actualResult = pokedexCellModel.numberText
    
    // Then
    XCTAssertEqual(actualResult, expectedResult)
}
```

We'd need to research how to add a unit test class, but I think it could be a good idea.

2022-05-15 01:27 UTC, mdb1 commented on Pokedex/Presentation/Pokedex/PokedexTableViewCell.swift
> +    func displayPokemon(name: String, number: Int, image: UIImage?) {
You can read more about the benefits of Unit testing [here](https://blog.pragmaticengineer.com/unit-testing-benefits-pyramid/)

2022-05-17 12:34 UTC, mdb1 commented on Pokedex.xcodeproj/project.pbxproj
> -// !$*UTF8*$!
This file is important, this one should not be removed. It's the one that contains the folder structure of the project

2022-05-17 12:35 UTC, mdb1 commented on Pokedex.xcodeproj/project.xcworkspace/contents.xcworkspacedata
> -<?xml version="1.0" encoding="UTF-8"?>
This one is also important, and should be kept in git

2022-05-17 12:35 UTC, mdb1 commented on Pokedex.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
> -{
This one is also important and should be kept in git

2022-05-17 13:05 UTC, mdb1 requested changes
There are some files that should not have been deleted, lets re-add them, let me know if you have troubles with that and we can look at it together

2022-05-18 04:46 UTC, maurigzo commented on Pokedex.xcodeproj/project.pbxproj
> -// !$*UTF8*$!
The file was added!

![image](https://user-images.githubusercontent.com/28616843/168959096-20a88fdf-bad8-4cb8-b52e-dee1a993f5e9.png)

2022-05-18 04:47 UTC, maurigzo commented on Pokedex.xcodeproj/xcuserdata/mauri.xcuserdatad/xcdebugger/Breakpoints_v2.xcbkptlist
> +   <Breakpoints>
File removed

2022-05-18 04:49 UTC, maurigzo commented on Pokedex/Presentation/Pokedex/PokedexTableViewCell.swift
> +    func displayPokemon(name: String, number: Int, image: UIImage?) {
Test file & unit test created. We should see where to run in Github the tests

2022-05-18 04:51 UTC, maurigzo commented on Pokedex.xcodeproj/xcuserdata/mauri.xcuserdatad/xcdebugger/Breakpoints_v2.xcbkptlist
>              filePath = "Pokedex/Presentation/Pokedex/PokedexViewController.swift"
File removed

2022-05-18 05:11 UTC, maurigzo commented on Pokedex.xcodeproj/project.xcworkspace/contents.xcworkspacedata
> -<?xml version="1.0" encoding="UTF-8"?>
The file was added!

![image](https://user-images.githubusercontent.com/28616843/168961757-860f874f-22d7-4c95-b8d6-2a4072c59ba2.png)

2022-05-18 05:11 UTC, maurigzo commented on Pokedex.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
> -{
The file was added!

![image](https://user-images.githubusercontent.com/28616843/168961801-d1fffe66-7dfb-49fc-b369-f9f17c72f7ef.png)

2022-05-18 11:44 UTC, mdb1 requested changes
The tests are not compiling due to the typo

2022-05-18 11:44 UTC, mdb1 commented on PokedexTests/Model/Pokemon/PokedexCellViewModelTests.swift
> +        let pokedexCellModel = PokedexCellViewModel(name: "Bauri", number: 5P, image: nil)
5P 👀👀

2022-05-18 13:09 UTC, maurigzo commented on PokedexTests/Model/Pokemon/PokedexCellViewModelTests.swift
> +        let pokedexCellModel = PokedexCellViewModel(name: "Bauri", number: 5P, image: nil)
Fixed! Sorry for that missclick

2022-05-21 03:31 UTC, merged